proxy_cache_path /usr/share/nginx/cache keys_zone=apt-cache:5m inactive=250d max_size=8g;
log_format cacheable '[$time_local] "$upstream_cache_status" $remote_addr - "$request" $status "$http_referer" $body_bytes_sent "$http_user_agent" ';
resolver 8.8.8.8 ipv6=off valid=180s;

map $request_uri $needs_bypass {
    ~InRelease 1;
    ~Release 1;
    ~Packages 1;
    ~.dsc 1;
}

server {
    listen 3142;
    server_name apt-ngnix;
    access_log /var/log/nginx/access.log cacheable;

    location = /status {
        stub_status;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }

    location / {
        proxy_pass http://$host/;
        proxy_cache_key "${host}-${uri}";
        include /etc/nginx/conf.d/stub-cache.inc;
    }
}

server {
    listen 3142;
    server_name deb.debian.org;
    access_log /var/log/nginx/access.log cacheable;

    location / {
        proxy_pass http://$host/;
        proxy_cache_key "debian-$uri";
        include /etc/nginx/conf.d/stub-cache.inc;
    }
}

server {
    listen 3142;
    server_name security.debian.org;
    access_log /var/log/nginx/access.log cacheable;

    location / {
        proxy_pass http://$host/;
        proxy_cache_key "debiansecurity-$uri";
        include /etc/nginx/conf.d/stub-cache.inc;
    }
}

# microsoft is normally HTTPs so a passthrough for caching vscode
server {
    listen 3142;
    server_name packages.microsoft.com;
    access_log /var/log/nginx/access.log cacheable;

    location / {
        include /etc/nginx/conf.d/stub-proxy.inc;
        proxy_pass https://packages.microsoft.com/;
        proxy_set_header Host "packages.microsoft.com";
        proxy_ssl_server_name on;
    }

    location /repos/code/pool/ {
        proxy_cache_key "microsoft-$uri";
        include /etc/nginx/conf.d/stub-cache.inc;

        proxy_pass https://packages.microsoft.com/repos/code/pool/;
        proxy_set_header Host "packages.microsoft.com";
        proxy_ssl_server_name on;
    }
}

# Docker is normally HTTPs so a passthrough for caching
server {
    listen 3142;
    server_name download.docker.com;
    access_log /var/log/nginx/access.log cacheable;

    location / {
        include /etc/nginx/conf.d/stub-proxy.inc;
        proxy_pass https://download.docker.com/;
        proxy_set_header Host "download.docker.com";
        proxy_ssl_server_name on;
    }

    location /linux/debian/ {
        proxy_cache_key "dockerdeb-$uri";
        include /etc/nginx/conf.d/stub-cache.inc;

        proxy_pass https://download.docker.com/linux/debian/;
        proxy_set_header Host "download.docker.com";
        proxy_ssl_server_name on;
    }

    location /linux/ubuntu/ {
        proxy_cache_key "dockerubuntu-$uri${slice_range}";

        proxy_pass https://download.docker.com/linux/ubuntu/;
        proxy_set_header Host "download.docker.com";
        proxy_ssl_server_name on;

        include /etc/nginx/conf.d/stub-cache.inc;
    }
}

